### ISSUE TITLE
SignatureError raised because client.new_preauthorization_url uses more url params when generating signiture

### ISSUE THREAD

**Issue by richtier** [gocardless/gocardless-python#27]
I am trying to "confirm a new pre-auth" in sandbox.

I generate a url using `gocardless.client.new_pre_authorization_url`, then I am confirming with `gocardless.client.confirm_resource` when the user clicks the form submit button.

More specifically, I am doing the following:

```py
       # generate the link
        return gocardless.client.new_pre_authorization_url(
            max_amount=1000.00,
            interval_length=1,
            interval_unit='month',
            name='A Name',
            state=user.id,
            calendar_intervals=True,
            user={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'company_name': self.name,
                'email': user.email
            }
        )
```
This creates a url to give to the user that links to a nice pre-populated form. So far so good.

However, on confirmation the problem start:

```py
        # confirming
        gocardless.client.confirm_resource(request.GET.dict())
```

At this point the `gocardless` library raises `SignatureError("Invalid signature when confirming resource")` [here](https://github.com/gocardless/gocardless-python/blob/master/gocardless/client.py#L314)

I see that `new_pre_authorization_url` generates the hmac signature using more of the url params than are used by `confirm_resource`:
```py
# params used by new_pre_authorization_url [here](https://github.com/gocardless/gocardless-python/blob/master/gocardless/urlbuilder.py#L152)
{
    'client_id': <client_id>,
     'nonce': <nonce>,
     'pre_authorization': {
         'calendar_intervals': True,
         'interval_length': 1,
         'interval_unit': 'month',
         'max_amount': 1000.0,
         'merchant_id': '<merchant id>',
         'name': 'Monofox Ask Peers',
         'user': {
             'company_name': u'A Name',
             'email': jimmy@jam.com',
             'first_name': u'jimmy',
             'last_name': u'jam'
         }
     },
     'state': 13L,
     'timestamp': '2015-05-28T18:50:05Z'
}
```
whereas when we confirm the pre auth
```py
# params used by `confirm_resource` [here](https://github.com/gocardless/gocardless-python/blob/master/gocardless/client.py#L332)
    {
        u'state': u'13'
        u'resource_uri': u'https://sandbox.gocardless.com/api/v1/pre_authorizations/<merchant id>',
        u'resource_type': u'pre_authorization',
        u'resource_id': u'<resource id>'
    }
```

When these params are each passed to `hmac.new` [here](https://github.com/gocardless/gocardless-python/blob/master/gocardless/utils.py#L34), of course they will return different signitures.

The `params` payload passed to `hmac.new` are so vastly different that this makes me think I might be using the api incorrectly?

**Comment by jacobpgn** [comment]
Hi @richtier!,

The params are meant to be different here - you generate one signature in `new_pre_authorization_url` which we use to check the link hasn't been manipulated, and then we generate a new signature for the return parameters (state, resource_uri, resource_type, and resource_id) so that you can verify that this customer really completed our payment pages.

It looks like you're using the right parameters, so the `SignatureError` most likely indicates that the library wasn't initialised correctly. At the point where you're calling `confirm_resource`, check that  `gocardless.environment` and `gocardless.set_details` are configured in exactly the same way as they were when generating the link and you should find that it confirms without errors.

If you're still having issues, just send over the resource ID you're trying to confirm to help@gocardless.com and we'll help you to debug!
